# Generated by Django 3.2.11 on 2022-02-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
